import { Component } from '@angular/core';

@Component({
	selector: 'ngwp-icon-defs',
	templateUrl: './icon-defs.component.html', // generated by `$ npm run svgstore`
	styleUrls: ['./icon-defs.component.less']
})

export class IconDefsComponent { }
